name: Frontend CI & Docker Build

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    #environment: kinder-ap-fe

    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      # ---------------- Checkout ----------------
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------- Node Setup ----------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      # ---------------- Install dependencies ----------------
      - name: Install dependencies
        run: npm ci

      # ---------------- Build React app ----------------
      - name: Build React app
        run: npm run build

      # ---------------- Docker Login ----------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image (build-number)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kinder-frontend:${{ env.BUILD_NUMBER }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kinder-frontend:${{ env.BUILD_NUMBER }}




      # # ---------------- Docker Build ----------------
      # - name: Build Docker image
      #   run: |
      #     docker build \
      #       -t ${{ secrets.DOCKERHUB_USERNAME }}/kinder-frontend:latest \
      #       -t ${{ secrets.DOCKERHUB_USERNAME }}/kinder-frontend:${{ env.BUILD_NUMBER }} \
      #       .

      # # ---------------- Docker Push ----------------
      # - name: Push Docker image
      #   run: |
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/kinder-frontend:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/kinder-frontend:${{ env.BUILD_NUMBER }}