name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: kinder-ap-fe

    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Basic Hello Steps
      - name: Print Hello
        run: echo "Hello World"

      - name: Print Second Message
        run: echo "This is the second jobbbbb"

      # 3️⃣ Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 4️⃣ Install Dependencies
      - name: Install Dependencies
        run: npm install

      # 5️⃣ Build React App
      - name: Build Application
        run: npm run build

      # 6️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7️⃣ Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kinder-frontend:build-${{ github.run_number }} .

      # 8️⃣ Tag Docker Image as Latest
      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/kinder-frontend:build-${{ github.run_number }} \
                     ${{ secrets.DOCKERHUB_USERNAME }}/kinder-frontend:latest

      # 9️⃣ Push Build Number Tag
      - name: Push Build Tag
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kinder-frontend:build-${{ github.run_number }}

      # 🔟 Push Latest Tag
      - name: Push Latest Tag
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kinder-frontend:latest